### ISSUE TITLE
Popular Tags Not Working For Me

### ISSUE THREAD

**Issue by BenQoder** [cviebrock/eloquent-taggable#60]
When I Do

`return $tags = \App\Job::popularTags(10);`
I Get Error
`(2/2) QueryException
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '? GROUP BY t.tag_id ORDER BY taggable_count DESC LIMIT ?' at line 1 (SQL: SELECT t.*, COUNT(t.tag_id) AS taggable_count FROM taggable_tags t LEFT JOIN taggable_taggables tt ON tt.tag_id=t.tag_id WHERE tt.taggable_type IS App\Job GROUP BY t.tag_id ORDER BY taggable_count DESC LIMIT 10)`

**Comment by cviebrock** [comment]
Fix coming shortly: version 3.2.1 (for Laravel 5.5) and 3.1.1 (for L5.4).

**Comment by benidixt** [comment]
I'm So Sorry, I Still Get Error After Update

`(2/2) QueryExceptionSQLSTATE[42000]: Syntax error or access violation: 1055 'haayaa.t.name' isn't in GROUP BY (SQL: SELECT t.*, COUNT(t.tag_id) AS taggable_count FROM taggable_tags t LEFT JOIN taggable_taggables tt ON tt.tag_id=t.tag_id WHERE tt.taggable_type = App\Job GROUP BY t.tag_id ORDER BY taggable_count DESC)
--
in Connection.php (line 664)`

**Comment by benidixt** [comment]
I Modified The TagService And Got It Working

`    public function getPopularTags(int $limit = null, $class = null, int $minCount = null): Collection
    {
        $sql = 'SELECT t.*, COUNT(t.tag_id) AS taggable_count FROM taggable_tags t LEFT JOIN taggable_taggables tt ON tt.tag_id=t.tag_id';
        $bindings = [];

        if ($class) {
            $sql .= ' WHERE tt.taggable_type = ?';
            $bindings[] = ($class instanceof Model) ? get_class($class) : $class;
        }

        $sql .= ' GROUP BY t.tag_id, t.name, t.normalized, t.created_at, t.updated_at';

        if ($minCount) {
            $sql .= ' HAVING taggable_count >= ?';
            $bindings[] = $minCount;
        }

        $sql .= ' ORDER BY taggable_count DESC';

        if ($limit) {
            $sql .= ' LIMIT ?';
            $bindings[] = $limit;
        }

        return Tag::fromQuery($sql, $bindings);
    }`

**Comment by cviebrock** [comment]
You changed the SQL to add those additional `GROUP BY` columns?  That actually isn't doing anything useful in the query, and may, in fact, mess up the counts.

Looking at your original error, I don't see where it's looking for `haayaa.t.name` in the query, so I suspect there is something else going on here.

What version of Laravel, the package, and database are you using?

**Comment by benidixt** [comment]
Im On Laravel 5.5. Using My MySql

**Comment by benidixt** [comment]
haayaa is the name of of the mysql database

**Comment by cviebrock** [comment]
But you can run this query directly in the DB, right?

```sql
SELECT t.*, COUNT(t.tag_id) AS taggable_count FROM taggable_tags t 
LEFT JOIN taggable_taggables tt ON tt.tag_id=t.tag_id 
WHERE tt.taggable_type = 'App\Job' 
GROUP BY t.tag_id 
ORDER BY taggable_count DESC
```

**Comment by benidixt** [comment]
That Returned Empty?. When I Run Directly

**Comment by benidixt** [comment]
But I Don't Think The Count Is Messed Up For Now.
Because I Keep Increasing The Tags And Everything Works Perfectly

**Comment by cviebrock** [comment]
If that SQL is returning an empty result set, but your SQL works:

```sql
SELECT t.*, COUNT(t.tag_id) AS taggable_count FROM taggable_tags t 
LEFT JOIN taggable_taggables tt ON tt.tag_id=t.tag_id 
WHERE tt.taggable_type = 'App\Job' 
GROUP BY t.tag_id, t.name, t.normalized, t.created_at, t.updated_at
ORDER BY taggable_count DESC
```

... then it's definitely not an issue with the package.

**Comment by benidixt** [comment]
I'm working on my windows. Xampp Enviroment, Maybe When I Switch Over To The Server (When I'm Done). Situation Might Change... Thanks Alot For Your Time

**Comment by cviebrock** [comment]
I just fixed another issue that might be related.  Can you try the latest version of the package (3.2.2 for Laravel 5.5, or 3.1.2 for Laravel 5.4), and let me know if that solves things?

**Comment by benidixt** [comment]
Not A Fix

**Comment by wppd** [comment]
I have the same problem. but it's so weird. 

If I run the sql directly in mysql, it works.

but via php, it just breaks.

**Comment by wppd** [comment]
problem found.
config/database.php
change mysql -> strict to false

**Comment by wppd** [comment]
@cviebrock I think may be you should group by the other columns.

**Comment by cviebrock** [comment]
@wppd @benidixt I apologize!  I didn't think of `strict` mode implications with my `groupBy()` call.

Can you take a second and try the `dev-master` branch again? I added all the columns to my group, so that should fix it for both strict and non-strict modes.  If it works, I'll tag a new release.

Thanks!

**Comment by wppd** [comment]
will run a test and let you know then

**Comment by cviebrock** [comment]
Gonna assume all is good now, so closing this and bumping the package

**Comment by cviebrock** [comment]
Version 3.2.3 should resolve your issues.

**Comment by crishellco** [comment]
This is still an issue with `v3.2.3`.

![image](https://user-images.githubusercontent.com/1878509/32302756-01663efa-bf2a-11e7-90b2-fe8e8a134268.png)

**Comment by cviebrock** [comment]
@crishellco Can you confirm that the above comes from a call to `Product::withAllTags($array)` and not the popular tags method? Based on the SQL, I'm assuming that's the case.

Unfortunately, I don't see an easy solution here.  The `GROUP BY` part of that clause would require the package (i.e. the Eloquent model) to know all the fields in `products.*` so that it could group by them when MySQL is in strict mode.

I'm not sure if there is a way to turn strict mode off on a per-query basis, which is really the only thing I can think of right now.

**Comment by hairmenu** [comment]
i think there is still an issue here 
`SELECT t.*, COUNT(t.tag_id) AS taggable_count FROM taggable_tags t` as it is, taggable_count will always be equal to 1.
I think it shoudl be `SELECT t.*, COUNT(**# tt**.tag_id) AS taggable_count FROM taggable_tags t`

**Comment by OlexandrPopov** [comment]
> Unfortunately, I don't see an easy solution here. The GROUP BY part of that clause would require the package (i.e. the Eloquent model) to know all the fields in products.* so that it could group by them when MySQL is in strict mode.

What do you think about selecting columns from the [information_schema.columns](https://dev.mysql.com/doc/refman/8.0/en/columns-table.html) table? There is already a [method](https://laravel.com/api/5.6/Illuminate/Database/Schema/Builder.html#method_getColumnListing) implemented in Laravel's query builder that can do it. However, it will add additional query:
```
select column_name as `column_name` from information_schema.columns where table_schema = ? and table_name = ?
```
> I'm not sure if there is a way to turn strict mode off on a per-query basis, which is really the only thing I can think of right now.

It's possible to change the sql_mode variable before the query execution and restore its value after. By default Laravel sets the following value:

```
SET sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
```

and it can be overridden like this:

```
SELECT @@sql_mode INTO @saved_sql_mode;
SET sql_mode = (SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY,', ''));
-- your select query goes here
SET sql_mode = @saved_sql_mode;

```
but I'm not sure there is a way to to execute multiple queries at once

**Comment by cviebrock** [comment]
This is an old ticket, and I think several issues are being conflated.  If there are still issues with strict mode and MySQL, please open another ticket.

**Comment by judgej** [comment]
This SQL strict mode thing is a big issue for us. We are rolling out sites across different database types, and we can't be shoving MySQL options and assumptions about the dialects of SQL they run into Azure SQL or Postgres. Is there no way to generate strict SQL grouping in the first place that works to, say, [SQL92 standard](http://dev.cs.ovgu.de/db/sybase9/help/dbugen9/00000284.htm)?

**Comment by MordiSacks** [comment]
This is my solution
```php
$taggable->whereHas('tags', function (Builder $q) {
    $q->whereIn('normalized', ['tag1', 'tag2', 'tag3']);
});
```
